apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytic-stack.fullname" . }}-grafana
  labels:
    {{- include "analytic-stack.labels" . | nindent 4 }}-grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "analytic-stack.selectorLabels" . | nindent 4 }}-grafana
