{{- if .Values.influx -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytic-stack.fullname" . }}-influx
  labels:
    {{- include "analytic-stack.labels" . | nindent 4 }}-influx
spec:
  type: {{ .Values.influx.service.type }}
  ports:
    - port: {{ .Values.influx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "analytic-stack.selectorLabels" . | nindent 4 }}-influx
{{- end }}