apiVersion: v1
kind: Secret
metadata:
  annotations:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ include "analytic-stack.fullname" . }}-secrets
type: Opaque
data:
  grafana_admin_password: {{ .Values.grafana.admin_password }}
  influx_admin_password: {{ .Values.influx.admin_password | default "somepass" | b64enc }}
  influx_user_password: {{ .Values.influx.user_password | default "somepass" | b64enc }}
